name: CSharp CI

on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'
      - name: Run unit checks
        run: dotnet test Timesheet.Test --filter FullyQualifiedName~Timesheet.Test.Unit
      - name: Run integration and E2E checks
        run: |
          Start-Process -NoNewWindow -FilePath "dotnet" -ArgumentList "run --project Timesheet"
          Start-Sleep -Seconds 10
          dotnet test Timesheet.Test --filter FullyQualifiedName~Timesheet.Test.Api
          dotnet test Timesheet.Test --filter FullyQualifiedName~Timesheet.Test.E2E